### ISSUE TITLE
backend code review - model.DataSet model.Project and model.*

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/wp6-repository#20]
There is repeating pattern of private field and getter setter methods. Is there good reason to have this pattern everywhere? I think DataSet and Project are mainly DTO objects reflecting the database items.

class DataSet{
private xx
public getXX() {return xx}
public setXX(_xx) { xx=_xx}
} 

Does it make sense to have just POJO class with public field, E.g. field id, name, ...:

class DataSet{
  public final Long id;
  public final String name;
}

**Comment by andreagia** [comment]
I completely agree and it was my mistake

Andrea

**Comment by andreagia** [comment]
Hi Tomas I have read well your comment now, the DataSet class are used as entity for JPA/hibernate

**Comment by TomasKulhanek** [comment]
OK. As I understand the Java frameworks, they depend heavily in order to access object fields using reflection. Then leave them as they are - but generating JSON from this objects fails as there is nested fields and other staff which violates POJO.
