### ISSUE TITLE
copy data on scientist request from repository server to Virtual Folder 

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/wp6-repository#22]
Create copy or move service to allow feature "copy data on scientist request" as from
http://internal-wiki.west-life.eu/index.php/D6.2:RepositoryArchitecture#Deployment

Currently, UI contains dialog to get source dataset and target D6.1 Virtual Folder directory url in wewbdav. 
- It can trigger copy(local_webdav_dir, remote_virtual_folder_url)
- Nice to have some progress bar

Sample shell script to recursive local copy at https://superuser.com/questions/523194/how-to-recursively-upload-a-directory-to-a-webdav-server-through-https-from-the

**Comment by andreagia** [comment]
Hi Tomas, in practice we need a service in spring backend that access and manage  webdav files, I’m new with webdav can I manage these file as standard filesystem or I have to mange these using webdav api ?

**Comment by andreagia** [comment]
I looked for some webdav client java what do you think about this project?

https://github.com/lookfirst/sardine

**Comment by TomasKulhanek** [comment]
I need a service 

- copy(localdir,webdavurl) - local dir is filesystem path accessible from Java process, webdavurl is endpoint capable withWEBDAV protocol,
- WEBDAV is extension to HTTP. We need only HTTP PUT request to send the desired file into the server. 
- Sardine client seems to be overkill for the purpose
- I did already sample code in different languages (except Java)
https://h2020-westlife-eu.gitbooks.io/virtual-folder-docs/content/doc/integration-guide/working-with-webdav.html

**Comment by andreagia** [comment]
Ok but with sardine this operation seams quite simple:

Sardine sardine = SardineFactory.begin("username", "password");
byte[] data = FileUtils.readFileToByteArray(new File("/file/on/disk"));
sardine.put("http://yourdavserver.com/adirectory/nameOfFile.jpg", data);

**Comment by TomasKulhanek** [comment]
This particular does not scale for files > 2GB. It will first read file to memory and then stream to server. Waste of resources.

**Comment by andreagia** [comment]
This allows you to HTTP PUT a file up on a webdav server. It takes an InputStream so that you don't have to buffer the entire file into memory first as a byte array.

Sardine sardine = SardineFactory.begin();
InputStream fis = new FileInputStream(new File("/some/file/on/disk.txt"));
sardine.put("http://yourdavserver.com/adirectory/nameOfFile.jpg", fis);

I can use FileInputStream

**Comment by TomasKulhanek** [comment]
> in dev-andrea I have made some update can you check if they work with your frontend

It doesn't. 

1. the name of method in WebDAVCopyUtils is misleading, it should be "copytowebdav" - I need to copy local file to webdav, not 'from'
2. I need to copy recursively all directory content - FileInputStream accepts only FILE not DIR, please add recursion over all file [docs.oracle.com/javase/8/docs/api/java/nio/file/Files](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#find-java.nio.file.Path-int-java.util.function.BiPredicate-java.nio.file.FileVisitOption...-)
3. Suggest some progressbar functionality. E.g. the number of all files and order of current file which is being coppied.

**Comment by andreagia** [comment]
on Service I have update WebDAVCopyUtils class can you try if it works?

**Comment by TomasKulhanek** [comment]
It doesn't. I'm going to fix it.

**Comment by TomasKulhanek** [comment]
files coppied into specified webdav endpoint recursively. new endpoint /copytask shows status of the task executed asynchronously on the backend, errors are logged with message only into the status.
