### ISSUE TITLE
return reference of newly created object instead of void

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/wp6-repository#27]
Current call of dataSetService.save(ds) returns void. I need to know the ID under which it was stored in DB. Return ID or by default newly created object instead of void in org.cirmmp.spring.service;

public interface DataSetService {
    DataSet save(DataSet dataSet);
}

**Comment by andreagia** [comment]
Try this:
After you have called dataSetService.save(dataSet)
call
Long DatSetID = dataSet.getId();


Andrea

**Comment by TomasKulhanek** [comment]
subsequent call of getId() solves this issue. However, is it thread safe? If another dataset will be created in the mean time - getId() may return incorrect Id of last saved by somebody else.

**Comment by andreagia** [comment]
The service that save in the database are marked with @Transactional, in principle they have to manage that the thread are safe

**Comment by TomasKulhanek** [comment]
OK. Closing this issue.

**Comment by chrishmorris** [comment]
Good call! It’s great to be working with someone who can spot that.

**Comment by TomasKulhanek** [comment]
Reopening. @Transactional does not guarantee threadsafe in the context of the web service. dataSetService.save(dataSet) should return either updated dataSet or at least datasetId.

**Comment by andreagia** [comment]
I have found that spring HibernateTemplate is thread-safe
https://books.google.it/books?id=DoInCgAAQBAJ&pg=PA307&lpg=PA307&dq=hibernatetemplate+thread+safe&source=bl&ots=aHwDt93LAN&sig=QAy2_QCWzjIScWuQXFfylOIfxlk&hl=it&sa=X&ved=0ahUKEwjbnqXlo8bZAhWIr6QKHUu0CjEQ6AEIZjAF#v=onepage&q=hibernatetemplate%20thread%20safe&f=false <https://books.google.it/books?id=DoInCgAAQBAJ&pg=PA307&lpg=PA307&dq=hibernatetemplate+thread+safe&source=bl&ots=aHwDt93LAN&sig=QAy2_QCWzjIScWuQXFfylOIfxlk&hl=it&sa=X&ved=0ahUKEwjbnqXlo8bZAhWIr6QKHUu0CjEQ6AEIZjAF#v=onepage&q=hibernatetemplate thread safe&f=false>
I can try to substitute the abstractdao used for the hibernate sessionFactory injection with hibernateTemplate

As test I have created a service called DatasetDaoImplH that use hibernateTempalte can you try if it work?

Andrea

**Comment by TomasKulhanek** [comment]
We probably don't understand each other. I don't see the implication HibernateTemplate is thread safe => web service is thread safe. I think it's not true, however, it's overkill for me to create some test which will prove it. I need to focus on frontend. Can you return dataset id in a save() and make the method  synchronized, please?

**Comment by andreagia** [comment]
Ok I will try to create a test to check if REST controller is thread safe

**Comment by TomasKulhanek** [comment]
I synchronized the two critical calls.
                synchronized (lock1) {
                    dataSetService.save(ds);
                    dto.id = ds.getId();
                }
Unfortunately this doesn't prevent other classes to ammend dataSetService.
