### ISSUE TITLE
Stateless CSRF protection

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/wp6-repository#30]
Spring framework implements one type of CSRF protection based on synchronizer tokens. 
Unfortunately it is not stateless and hard to implement in pure HTML, AJAX client.
Spring pregenerates some html tags within JSP pages on each GET request, which can be used by subsequent POST request. As GET request change the server state, it violates one of the main RESTful constraint and as a consequence it's hard to implement it in different technology than JSP.

Per recomendation given by OWASP Foundation at 
https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet

There are approaches that do require no server side state:

- Double Cookie Defense
- Encrypted Token Pattern
- Custom Header - e.g., X-Requested-With: XMLHttpRequest 

I've tested Double Cookie Defense and Custom Header for Spring framework, which seems to work for RestCon. Thus we need to decide among following options:

1. Have stateless csrf protection for REST service (RestCon) and default (stateful) csrf protection for JSP pages and non-REST api (AppController)

OR 

2. Have only stateless csrf protection - needs to modify JSP pages

OR

3.  Have only statefull protection (SPRING default) - violating REST, introducing proprietary hack and possible other vulnerabilities.

**Comment by andreagia** [comment]
Can you add something like this:

We can’t submit the CSRF token as a parameter if we’re using JSON; instead we can submit the token within the header.

We’ll first need to include the token in our page – and for that we can use meta tags:

1
2
<meta name="_csrf" content="${_csrf.token}"/>
<meta name="_csrf_header" content="${_csrf.headerName}"/>
Then we’ll construct the header:

1
2
3
4
5
6
var token = $("meta[name='_csrf']").attr("content");
var header = $("meta[name='_csrf_header']").attr("content");
 
$(document).ajaxSend(function(e, xhr, options) {
    xhr.setRequestHeader(header, token);
});

**Comment by TomasKulhanek** [comment]
This is already in some stackoverflow advice, which was downvoted as  ${_csrf.token} is not HTML – it’s server rendered JSP tag that cannot be served by Apache. It violates the principle of independent frontend. Additional to that my code performs additional AJAX calls to retrieve data from backend API based on user UI context and all these requests change the internal CSRF thus _csrf.token after additional AJAX calls will be invalid.

Tomas

**Comment by andreagia** [comment]
Hi Tomas I have found some solution for reactjs.
this import react-cookie library and take the csrf token from cookies 

<form action="/perform-logout" method="post">
                  <input type="hidden" name="_csrf" value={Cookie.load('XSRF-TOKEN')}/>
                   <input type="submit" className="btn btn-primary btn-block" value="Sign Out"/>
                </form> 
otherwise we can disable the csrf on spring security configuration adding disable in SecurityConfiguration.java at line 81

.antMatchers("/login","/static/**").permitAll().and().csrf();
.antMatchers("/login","/static/**").permitAll().and().csrf().disable();

**Comment by TomasKulhanek** [comment]
Hi Andrea,
Cookie solution is not solution for our scenario. I already tried it and it does not solve invalid CSRF token when multiple AJAX calls are performed.
I did already disabled csrf().disable() and put custom CSRF filter.
The questions in this issue is whether use 1) combination of both ( disable csrf only for some endpoints and set custom csrf filter which is now in dev-tomas)
2) have all csrf stateless (in dev-tomas)
3) stateful – current csrf

I prefer 1) or 2). I do not prefer 3 as it is dirty – all are hacking via cookies and doesn’t prevent multiple csrf token generated for one page.
If 1), then how to disable csrf only for /restcon.

Tomas

**Comment by andreagia** [comment]
can you try this in spring security configuration

.csrf()
             .ignoringAntMatchers(“/restcon/**")

**Comment by TomasKulhanek** [comment]
Thus suggested solution: 
For all except /restcon endpoint: CSRF protection based on synchronizer token (default for SPRING). For /restcon endpoint: CSRF protection based on custom header (recommended for stateless REST services).
```java
//enabling csrf for all except for restcon endpoints
.csrf().ignoringAntMatchers("/restcon/**").and()
// custom csrf filter for restcon endpoint
.antMatcher("/restcon/**").addFilterBefore(new StatelessCSRFFilter(), CsrfFilter.class); 
```
