### ISSUE TITLE
Get authenticated user information from the request or context within REST controller

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/wp6-repository#33]
- [ ] AJAX call to /staff/restcon/user - do not return user information - seems that the request is not authenticated - ssoId: "anonymousUser" even previous login with "user:..." was done

There seems to not work properly
- [x] http://localhost:8080/ click on Staff - giving demo user/user credentials  - should redirect to staff/index.html not to list of users, after redoing the same - it is redirected
- [x] http://localhost:8080/staff/restcon/user should return id of logged in user - not redirecting to login page
- [x] going to "Staff access" don't ask for credentials
- [x] going to "Admin access" fails on NPE

on vagrant environment dev-tomas branch,

- [x] Request method 'POST' not supported, when trying to login, csrf() enabled cause, workaround  temporary disabled CSRF, moved to issue #32 
- [x] going to "Staff access" asks for credentials - do not redirect to staff pages, fixed by enabling successHandler()
- [x] going to "Admin access" is ok

**Comment by TomasKulhanek** [comment]
SecurityContextHolder.getContext().getAuthentication(); returns "anonymousUser" instead of logged in user. The same with HttpServletRequest request.getUserPrincipal(); which returns null;

**Comment by andreagia** [comment]
Tomas which  restcon method you call to authenticate ?

**Comment by TomasKulhanek** [comment]
I do not call any method.

1.       user goes to localhost:8080

2.       click on Staff access – link to /admin/login?next=../staff/index.html

3.       Spring authentication page is present – fill user:user enter – it sends POST request to backend with auth information

4.       Redirected to /staff/index.html

5.       AJAX call from here goes to /staff/restcon/user

6.       Handled by listOrder() the subsequent call of checkAuthentication() and SecurityContextHandler.getContext().getAuthentication() do not work.

I expect that “authenticate” is done between steps 3. and 4. By Spring SecurityContext

Tomas

**Comment by andreagia** [comment]
Hi Tomas the new configuration of spring security bypass the authentication, this is the reason hat you don't find the user after login

Andrea

**Comment by TomasKulhanek** [comment]
I need clarification. How the security is maintained. I thought that cookies set by server during session should be enough to keep user logged in.
Tomas

**Comment by TomasKulhanek** [comment]
- changed endpoint from /staff/index.html to /admin/index.html
- cookie is valid for context /admin ... any call to /admin/restcon is authenticated with this cookie and recognized by Spring framework
