### ISSUE TITLE
Consider to use lombok Getter and Setter annotation 

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/wp6-repository#34]
What about to reincarnate POJO and **Never write public int getFoo() {return foo;} again** :+1: 
https://projectlombok.org/features/GetterSetter

**Comment by andreagia** [comment]
In my dev-andre i have added project lombock in pom.xml and i would like to
use it for synchronize method

Il 07 mar 2018 1:13 PM, "Tomas Kulhanek" <notifications@github.com> ha
scritto:

**Comment by TomasKulhanek** [comment]
Used in DTO's classes and in some other methods. Compilation OK in MAVEN. Inside IntelliJ or Eclipse, there is needed to install Lombok plugin  https://plugins.jetbrains.com/plugin/6317-lombok-plugin https://projectlombok.org/setup/eclipse
